pipeline {
    agent any
    stages{      
         stage('Dependencies') {
            steps {
                sh 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64'
                sh 'export PATH=$PATH:/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin'
                sh 'echo $JAVA_HOME'    
            }
        }    
        stage('Clean Build') {
            steps {
                dir("ListView") {
                    sh "pwd"
                    sh 'ls -al'
                    sh './gradlew clean'
                }   
            }
        }
        
        stage('Sauce Testing'){
            when {
                branch 'java'
            }
            steps {
                dir("ListView") {
                    sauce('sauce_aceess_key') {
                        // some block
                    }
                }
            }
        }
        
        stage('Debug apk creation ') {
          when {
                branch 'develop' 
            }
            steps {
                dir("ListView") {
                    sh "pwd"
                    sh "./gradlew assembleDebug"
                }
            }
        }
        stage("Send Debug apk over email"){
            when {
                branch 'java' 
            }
            steps {
                script {
                    def isStartedByUser = currentBuild.rawBuild.getCause(hudson.model.Cause$UserIdCause) != null
                    echo ("Testing: " + isStartedByUser)
                    wrap([$class: 'BuildUser']) {
                        sh 'echo "${BUILD_USER}"'
                        if ("${BUILD_USER_ID}" == '') {
                            sh 'echo "build started by git commit"'
                        }else {
                            // Get the input
                            def userInput = input( 
                                            id: 'userInput',
                                            message: 'Enter email',
                                            parameters: [
                                                [$class: 'StringParameterDefinition',
                                                defaultValue: '',
                                                description: 'Pleae enter your email, otherwise default behavoir will be executed by script',
                                                name: 'UserEmail']
                                            ]
                                           )
                            echo ("Image tags: "+ userInput)
                            if ( userInput == '' ){
                                emailext body: 'A Test EMail', subject: 'Test', to: '$DEFAULT_RECIPIENTS' 
                                sh 'echo "build started by ${BUILD_USER_EMAIL}"'
                            }else {
                                echo ("build started by: " + userInput ) 
                            }
                        }
                    }
                }
            }
        }
        stage('Release apk creation ') {
          when {
                branch 'master' 
            }
            steps {
                dir("ListView") {
                    sh "pwd"
                }
            }
        }
        stage("Send Release apk over email "){
            when {
                branch 'master'
            }
            steps {
                emailext body: 'A Test EMail',
                    subject: 'Test',
                    to: '$DEFAULT_RECIPIENTS'    
            }
        }
    }
}
