pipeline {
    agent any
    stages{      
        stage('Set Current User') {
            steps {
                script {
                    wrap([$class: 'BuildUser']) {
                        sh 'echo "${BUILD_USER}"'
                    }
                }
            }
        }
         stage('Dependencies') {
            steps {
                sh 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64'
                sh 'export PATH=$PATH:/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin'
                sh 'echo $JAVA_HOME'    
            }
        }    
        stage('Clean Build') {
            steps {
                dir("ListView") {
                    sh "pwd"
                    sh 'ls -al'
                    sh './gradlew clean'
                }   
            }
        }
        
        stage('Sauce Testing'){
            when {
                branch 'java'
            }
            steps {
                dir("ListView") {
                    sauce('sauce_aceess_key') {
                        // some block
                    }
                }
            }
        }
        
        stage('Debug apk creation ') {
          when {
                branch 'develop' 
            }
            steps {
                dir("ListView") {
                    sh "pwd"
                    sh "./gradlew assembleDebug"
                }
            }
        }
        stage("Send Debug apk over email"){
            when {
                branch 'develop' 
            }
            steps {
                script {
                    wrap([$class: 'BuildUser']) {
                        sh 'echo "${BUILD_USER}"'
                        if ($BUILD_USER_ID == '') {
                            sh 'echo "build started by git commit"'
                        }else {
                            sh 'echo "build started by ${BUILD_USER_EMAIL}"'
                        }
                    }
                }
            }
        }
        stage('Release apk creation ') {
          when {
                branch 'master' 
            }
            steps {
                dir("ListView") {
                    sh "pwd"
                }
            }
        }
        stage("Send Release apk over email "){
            when {
                branch 'master'
            }
            steps {
                emailext body: 'A Test EMail',
                    subject: 'Test',
                    to: '$DEFAULT_RECIPIENTS'    
            }
        }
    }
}
